project_id = "eyyikioaxidymwaojbks"

[functions.send-contact-email]
verify_jwt = false

[functions.send-2fa-code]
verify_jwt = false

[functions.verify-2fa-code]
verify_jwt = false

[functions.chatbot]
verify_jwt = false